# ---

- name: Docker Playbook
  hosts: base
  connection: local
  gather_facts: true
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - ansible-docker

  pre_tasks:
    - set_fact: is_amazon_linux
      when: ansible_distribution == "Amazon"
    - set_fact: ansible_distribution_major_version=6
      when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA"
